
const template = {
  "playerID": "6652058",
  "playerNickname": "Mirradin",
  "saveDate": "2022-12-28T20:28:54.700Z",
  "itemInCollection": 55,
  "itemInUnlocks": 79,
  "itemInSecrets": 52,
  "SelectedCharacter": "NOSTRO",
  "SelectedStage": "FOREST",
  "SelectedHyper": false,
  "SelectedHurry": false,
  "SelectedMazzo": true,
  "SelectedLimitBreak": false,
  "SelectedInverse": false,
  "SelectedReapers": false,
  "SelectedGoldenEggs": true,
  "SelectedArcana": 0,
  "SelectedBGMSave": false,
  "SelectedBGM": "BGM_Tower",
  "SelectedBGMMod": "Normal",
  "SelectedMaxWeapons": 6,
  "Fullscreen": false,
  "Version": 12118,
  "Coins": 8909343,
  "RunCoins": 4997.250000000001,
  "RunEnemies": 21923,
  "RunPickups": [
    "ROAST",
    "ROAST",
    "OROLOGION",
    "ROAST",
    "ROAST",
    "COINBAG1",
    "TREASURE",
    "STATS_TREASURE_1",
    "VACUUM",
    "COINBAG1",
    "COINBAGMAX",
    "COINBAG1",
    "COINBAG1",
    "TREASURE",
    "STATS_TREASURE_1",
    "TREASURE",
    "STATS_TREASURE_1",
    "ROAST",
    "TREASURE",
    "STATS_TREASURE_1",
    "COINBAG1",
    "TREASURE",
    "STATS_TREASURE_1",
    "OROLOGION",
    "TREASURE",
    "STATS_TREASURE_1",
    "ROSARY",
    "COINBAG1",
    "ROAST",
    "TREASURE",
    "STATS_TREASURE_1",
    "OROLOGION",
    "TREASURE",
    "STATS_TREASURE_1",
    "ROAST",
    "ROAST",
    "COINBAG1",
    "ROSARY",
    "ROAST",
    "COINBAG1",
    "OROLOGION",
    "ROAST",
    "COINBAG1",
    "COINBAG1",
    "GILDED",
    "COINBAG1",
    "COINBAG1",
    "ROAST",
    "COINBAG1",
    "COINBAG1",
    "COINBAG1",
    "ROAST",
    "TREASURE",
    "STATS_TREASURE_2",
    "ROAST",
    "ROAST",
    "COINBAG1",
    "TREASURE",
    "STATS_TREASURE_1",
    "TREASURE",
    "STATS_TREASURE_1",
    "COINBAG1",
    "GILDED",
    "COINBAG1",
    "COINBAG1",
    "COINBAG1",
    "TREASURE",
    "STATS_TREASURE_1",
    "COINBAG2",
    "ROAST",
    "ROAST",
    "ROAST",
    "ROAST",
    "ROAST",
    "ROAST",
    "COINBAG2",
    "COINBAG2",
    "COINBAG2",
    "COINBAG2"
  ],
  "RunPickups_Coins": 271,
  "LifetimeCoins": 6721.25,
  "TotalCoins": 7482.25,
  "BeginnersLuck": 6,
  "RunFever": 132.75000000000003,
  "RunHunger": 0,
  "LifetimeSurvived": 3859,
  "LifetimeHeal": 734.095392,
  "OwO": 0,
  "CompletedHurries": 0,
  "ReducePhysics": true,
  "ClassicMusic": true,
  "VisuallyInvertStages": true,
  "HideProgress": false,
  "SoundsEnabled": true,
  "MusicEnabled": true,
  "SoundsVolume": 0.5,
  "MusicVolume": 0.5,
  "FlashingVFXEnabled": true,
  "JoystickVisible": false,
  "DamageNumbersEnabled": true,
  "StreamSafeEnabled": true,
  "hideXPBar": false,
  "CheatCodeUsed": false,
  "HasKilledTheFinalBoss": false,
  "HasSeenFinalFireworks": false,
  "Language": "en",
  "ShowQuitDescription": false,
  "HideCompletedAchievements": false,
  "PlayedRNJ": 0,
  "ShowPickups": false,
  "ShowSmallMapIcons": true,
  "TwitchUsername": "",
  "LongestFever": 16460.689999929073,
  "HighestFever": 201.75000000000003,
  "HasUsedMirror": false,
  "HasUsedTrumpet": false,
  "BoughtCharacters": [
    "ANTONIO",
    "IMELDA",
    "CIRO",
    "DOMMARIO",
    "EXDASH",
    "GENNARO",
    "GERMANA",
    "MORTACCIO",
    "CAMILLO",
    "PASQUALINA",
    "PORTA",
    "CROCI",
    "LAMA",
    "CAVALLO",
    "POPPEA",
    "CRISTINA",
    "PUGNALA",
    "SIGMA",
    "MARIA",
    "GIOVANNA",
    "TATANKA",
    "CONCETTA",
    "FEBBRA",
    "PINO",
    "VERANDA",
    "PANINI",
    "NOSTRO"
  ],
  "BoughtPowerups": [
    "POWER",
    "POWER",
    "POWER",
    "POWER",
    "POWER",
    "REGEN",
    "REGEN",
    "REGEN",
    "REGEN",
    "REGEN",
    "MAXHEALTH",
    "MAXHEALTH",
    "MAXHEALTH",
    "ARMOR",
    "ARMOR",
    "ARMOR",
    "AREA",
    "AREA",
    "SPEED",
    "SPEED",
    "COOLDOWN",
    "COOLDOWN",
    "DURATION",
    "DURATION",
    "AMOUNT",
    "MOVESPEED",
    "MOVESPEED",
    "MAGNET",
    "MAGNET",
    "LUCK",
    "LUCK",
    "LUCK",
    "GROWTH",
    "GROWTH",
    "GROWTH",
    "GROWTH",
    "GROWTH",
    "GREED",
    "GREED",
    "GREED",
    "GREED",
    "GREED",
    "SHIELD",
    "REVIVAL",
    "CURSE",
    "CURSE",
    "CURSE",
    "CURSE",
    "CURSE"
  ],
  "DisabledPowerups": [
    "CURSE"
  ],
  "CollectedWeapons": [
    "WHIP",
    "MAGIC_MISSILE",
    "POWER",
    "HOLYBOOK",
    "HOLYWATER",
    "LAUREL",
    "AXE",
    "ARMOR",
    "FIREBALL",
    "MAGNET",
    "KNIFE",
    "GARLIC",
    "SPEED",
    "AMOUNT",
    "COOLDOWN",
    "AREA",
    "HELLFIRE",
    "HOLY_MISSILE",
    "THOUSAND",
    "BORA",
    "LIGHTNING",
    "SILF",
    "LANCET",
    "GROWTH",
    "LUCK",
    "MAXHEALTH",
    "LOOP",
    "MOVESPEED",
    "CROSS",
    "HEAVENSWORD",
    "SILF2",
    "DURATION",
    "VESPERS",
    "SILF3",
    "PENTAGRAM",
    "SIRE",
    "DIAMOND",
    "REGEN",
    "REVIVAL",
    "VORTEX",
    "SCYTHE",
    "ROCHER",
    "PANDORA",
    "CURSE",
    "GREED",
    "VAMPIRICA",
    "GOLD",
    "RIGHT",
    "LEFT",
    "CHERRY",
    "FLOWER",
    "BONE",
    "VENTO",
    "GUNS",
    "GUNS2",
    "GUNS3",
    "SILVER",
    "SHROUD",
    "CORRIDOR",
    "TRAPANO",
    "TRIASSO1",
    "TRAPANO2",
    "TRIASSO2",
    "TRIASSO3",
    "GUNS_COUNTER",
    "GUNS2_COUNTER",
    "SILF_COUNTER",
    "SILF2_COUNTER",
    "GATTI_COUNTER",
    "GATTI",
    "STIGRANGATTI",
    "SONG",
    "MANNAGGIA",
    "CANDYBOX",
    "VICTORY",
    "SOLES",
    "VENTO2",
    "CART2",
    "ROBBA",
    "JUBILEE",
    "MISSPELL",
    "MISSPELL2",
    "CANDYBOX2"
  ],
  "UnlockedWeapons": [
    "WHIP",
    "VAMPIRICA",
    "MAGIC_MISSILE",
    "KNIFE",
    "AXE",
    "HOLYBOOK",
    "HOLYWATER",
    "SIRE",
    "LAUREL",
    "VENTO2",
    "TRIASSO2",
    "TRIASSO3",
    "SOLES",
    "MISSPELL2",
    "POWER",
    "ARMOR",
    "LIGHTNING",
    "FIREBALL",
    "GARLIC",
    "LUCK",
    "MAGNET",
    "SPEED",
    "AREA",
    "AMOUNT",
    "COOLDOWN",
    "GROWTH",
    "MOVESPEED",
    "MAXHEALTH",
    "SILF",
    "CHERRY",
    "LANCET",
    "PENTAGRAM",
    "CROSS",
    "SILF2",
    "REVIVAL",
    "REGEN",
    "DURATION",
    "DIAMOND",
    "BONE",
    "FLOWER",
    "PANDORA",
    "GREED",
    "GOLD",
    "SILVER",
    "LEFT",
    "RIGHT",
    "CURSE",
    "GUNS",
    "GUNS2",
    "TRIASSO1",
    "VENTO",
    "TRAPANO",
    "GATTI",
    "SONG",
    "ROBBA",
    "CANDYBOX",
    "VICTORY",
    "CART2",
    "JUBILEE",
    "MISSPELL"
  ],
  "UnlockedCharacters": [
    "DOMMARIO",
    "CROCI",
    "CAVALLO",
    "CIRO",
    "CAMILLO",
    "PORTA",
    "GERMANA",
    "CRISTINA",
    "ASSUNTA",
    "LAMA",
    "MORTACCIO",
    "TATANKA",
    "FINO",
    "SIGMA",
    "PUGNALA",
    "CONCETTA",
    "PINO",
    "FEBBRA",
    "GIOVANNA",
    "POPPEA",
    "AMBROGIO",
    "PAVONE",
    "ARENGIJUS",
    "PANTALONE",
    "SCOREJ",
    "MARIA",
    "PEPPINO",
    "BOROS",
    "AVATAR",
    "DRAGOGION",
    "NEO",
    "GRAZIELLA",
    "VERANDA",
    "NOSTRO",
    "EXDASH",
    "PANINI",
    "SMITH"
  ],
  "CollectedItems": [
    "ROAST",
    "COINBAG1",
    "TREASURE",
    "COINBAG2",
    "CLOVER",
    "VACUUM",
    "OROLOGION",
    "RELIC_GRIMOIRE",
    "GILDED",
    "RELIC_MAP",
    "RELIC_GOUDA",
    "NFT",
    "ROSARY",
    "RELIC_TEAR",
    "ALWAYS_COINBAG2",
    "COINBAGMAX",
    "RELIC_RANDOMAZZO",
    "RELIC_NOSEGLASSES",
    "LITTLEHEART",
    "COFFIN",
    "RELIC_GLASSMASK",
    "RELIC_GOLDENEGG",
    "RELIC_YELLOW",
    "RELIC_BANGER",
    "RELIC_GGOSPEL",
    "RELIC_SECRETS",
    "RELIC_MIRROR",
    "RELIC_TRUMPET"
  ],
  "Achievements": [
    "Defeat5000Enemies",
    "Destroy20Candles",
    "Eat5PotRoast",
    "FindAClover",
    "FindAVacuum",
    "GetHolyBookToLevel4",
    "GetHolyWaterToLevel4",
    "GetMagicMissileToLevel7",
    "Have6DifferentWeapons",
    "Earn5000CoinsInASingleRun",
    "ReachLV20InMadForest",
    "ReachLV10",
    "ReachLV5",
    "Survive1Minute",
    "Survive10Minutes",
    "Defeat100KEnemies",
    "Defeat3000Buers",
    "DefeatBossLibrary",
    "FindGrimoire",
    "FindAnOrologion",
    "GetFireWandToLevel4",
    "GetGarlicToLevel7",
    "ReachLV40InLibrary",
    "Survive20Minutes",
    "EvolveMagicWand",
    "EvolveKnife",
    "EvolveSantaWater",
    "EvolveFireWand",
    "Unlock3Hypers",
    "DefeatBossPlant",
    "FindGouda",
    "FindMilkyWayMap",
    "FindARosary",
    "GetLightningRingToLevel4",
    "GetPeachoneToLevel7",
    "Recover1000HP",
    "ReachLV60InDairyPlant",
    "Survive20MinutesWithCross",
    "EvolveLightning",
    "EvolveCross",
    "Unlock2Hypers",
    "DefeatBossTower",
    "FindSorceressTears",
    "FindRandomazzo",
    "GetPentagramToLevel7",
    "FindRandomazzoT06",
    "ReachLV99WithGennaro",
    "FindYellowSignS5",
    "Survive5MinutesWithKnife",
    "See50Items",
    "EvolveKingBible",
    "EvolvePentagram",
    "UniteBirds",
    "Unlock3Hypers_Correct",
    "DefeatBossChapel",
    "FindCoffinStage5",
    "GetRunetracerToLevel7",
    "ReachLV99WithPasqualina",
    "Survive5MinutesWithDiamond",
    "Survive20MinutesWithCurse",
    "See60Items",
    "EvolveAxe",
    "EvolveGarlic",
    "EvolveRunetracer",
    "Unlock4Hypers",
    "Defeat3000Skeletons",
    "Defeat3000Hydra",
    "Have6Evolutions",
    "ReachLV99WithLama",
    "See70Items",
    "GetTorroneToLevel9",
    "BuyGlassMask",
    "FindAStoneMask",
    "EvolveWhip",
    "FindYellowSign",
    "FindMagicBanger",
    "ReachLV99WithKroci",
    "See80Items",
    "DefeatBossChapel2",
    "FindGGospel",
    "Survive30MinutesWithAxe",
    "ObtainAllRelics",
    "FindForbiddenScroll",
    "Survive30MinutesInBoneZone",
    "ObtainGraciasMirror",
    "ObtainSeventhTrumpet",
    "FindCoffinStage1",
    "FindCoffinStage4",
    "ReachLV99WithPugnala",
    "Survive31MinutesInTower",
    "ReachLV80InverseTower",
    "Survive10MinutesWithGuns",
    "Survive15MinutesWithGuns",
    "See90Items",
    "ObtainTheInfiniteCorridor",
    "ObtainTheCrimsonShroud",
    "EvolveGuns",
    "DefeatBossMadForest",
    "Survive31MinutesInForest",
    "GalloDivano",
    "Unlock5Hypers",
    "Survive15MinutesWithWind",
    "Survive15MinutesInBossRash",
    "FindCoffinStage2",
    "ReachLV99WithConcetta",
    "Survive15MinutesWithShadow",
    "See100Items",
    "EvolveShadow",
    "EvolveBracelet",
    "FindCoffinStage3",
    "ReachLV99WithGiovanna",
    "Survive15MinutesWithGatti",
    "EvolveGatti",
    "Survive31MinutesInLibrary",
    "ReachLV99WithPoppea",
    "Survive15MinutesWithSong",
    "EvolveSongOfMana",
    "Defeat6000StageKillers",
    "ReachLV99WithPorta",
    "Banish10Items",
    "Survive30MinutesInGreenAcres",
    "EvolveWind",
    "EvolveAll",
    "ReachLV99WithChristine",
    "Survive31MinutesInDairyPlant",
    "Defeat100kWithSigma",
    "ReachLV99WithDommario",
    "ReachLV99WithPoe",
    "Survive15MinutesInMolise",
    "ReachLV99WithAntonio",
    "Survive15MinutesInMoongolow",
    "ReachLV99WithClerici",
    "ReachLV99WithImelda",
    "Defeat3000Milk",
    "ReachLV99WithArca",
    "ReachLV100WithMortaccio",
    "ReachLV100WithOsole",
    "ReachLV100WithCavallo",
    "ReachLV100WithRamba",
    "ReachLV100WithAmbrojoe",
    "GreatestJubilee",
    "CompleteCollection"
  ],
  "Secrets": [],
  "UnlockedStages": [
    "FOREST",
    "BONEZONE",
    "CHAPEL",
    "GREENACRES",
    "LIBRARY",
    "MACHINE",
    "MOLISE",
    "RASH",
    "SINKING",
    "STAGEX",
    "TOWER",
    "TOWERBRIDGE",
    "WAREHOUSE",
    "MOONSPELL"
  ],
  "UnlockedHypers": [
    "BONEZONE",
    "CHAPEL",
    "FOREST",
    "GREENACRES",
    "LIBRARY",
    "MOLISE",
    "RASH",
    "SINKING",
    "TOWER",
    "TOWERBRIDGE",
    "WAREHOUSE"
  ],
  "UnlockedPowerUpRanks": [
    "BANISH",
    "BANISH",
    "PANDORA",
    "BANISH",
    "SKIP",
    "BANISH",
    "SKIP",
    "BANISH",
    "SEAL",
    "SKIP",
    "SKIP",
    "SKIP",
    "REROLL",
    "REROLL",
    "REROLL",
    "REROLL",
    "REROLL"
  ],
  "UnlockedArcanas": [
    0,
    1,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    2,
    20,
    21,
    3,
    4,
    5,
    6,
    7,
    8,
    9
  ],
  "KillCount": {
    "BAT1": 518,
    "BAT2": 663,
    "BAT3": 1564,
    "BAT4": 522,
    "BAT5": 93,
    "BAT6": 0,
    "BATSWARM": 1944,
    "ZOMBIE": 1637,
    "SKELETON": 3865,
    "SKELETON2": 0,
    "SKELETON3": 0,
    "SKELETON4": 0,
    "WEREWOLF": 1923,
    "GHOST": 1644,
    "GHOST2": 0,
    "GHOSTSWARM": 544,
    "FLOWER": 305,
    "MUDMAN1": 2396,
    "MUDMAN2": 2339,
    "test": 0,
    "BOSS_WEREWOLF": 1,
    "BOSS_WEREWOLF2": 0,
    "MUD": 0,
    "BUER": 0,
    "MUMMY": 0,
    "ECTO1": 0,
    "ECTO2": 0,
    "WITCH1": 0,
    "WITCH2": 0,
    "MEDUSA1": 0,
    "MEDUSA1_FAST": 0,
    "MEDUSA2": 0,
    "MEDUSA2_AGGRO": 0,
    "MEDUSA2_FAST": 0,
    "DULL0": 0,
    "DULL1": 0,
    "DULL2": 0,
    "SKULL2_SCALING": 0,
    "SKULL2_EASY": 0,
    "SKULL2_SWARM": 0,
    "BOSS_SKULL2": 0,
    "SHADEBLUE": 0,
    "SHADERED": 0,
    "SKULLNOAURA": 0,
    "PILE4": 0,
    "PILE4_SCALED": 0,
    "XLSKELETON": 0,
    "BOSS_XLSKELETON": 0,
    "SKELEPANTHER": 0,
    "SKELEGLOW": 0,
    "SKELETONE": 0,
    "SKELEWING_ZONE": 0,
    "SKELENIN_ZONE": 0,
    "XLMAGIO": 0,
    "XLBAT": 1776,
    "XXLBAT": 0,
    "XLMUMMY": 2306,
    "XLMANTIS": 284,
    "XLFLOWER": 993,
    "XLMEDUSA": 0,
    "BOSS_XLMUMMY": 1,
    "BOSS_XLBAT": 0,
    "BOSS_XLMANTIS": 2,
    "BOSS_XLFLOWER": 1,
    "BOSS_XLDEATH": 0,
    "BOSS_XLDEATH2": 0,
    "BOSS_XLTRICKSTER": 0,
    "BOSS_XLSTALKER": 0,
    "BOSS_XLDROWNER": 0,
    "BOSS_ECTO": 0,
    "BOSS_MUD": 0,
    "BOSS_BUER": 0,
    "BOSS_XLMEDUSA": 0,
    "BOSS_COUNT1": 0,
    "BOSS_COUNT2": 0,
    "BOSS_MEDUSA1": 0,
    "BOSS_WITCH2": 0,
    "BOSS_XLLEDA": 2,
    "BOSS_NOOB": 0,
    "SKULLINO": 0,
    "SKULOROSSO": 0,
    "SKELANGUE": 0,
    "SKETAMARI": 0,
    "DEVIL1": 0,
    "DEVIL3": 0,
    "ARMOR1": 0,
    "ARMOR2": 0,
    "SKELEWING_INO": 0,
    "BOSS_HARPY": 0,
    "IMP": 0,
    "HARPY": 0,
    "HARPYV": 0,
    "PANTHER": 0,
    "POLTER_DEST": 0,
    "POLTER": 0,
    "BOSS_PANTHER": 0,
    "XLDRAGON1": 0,
    "XLDRAGON2": 0,
    "XLDRAGON1_FLAG": 0,
    "XLDRAGON2_FLAG": 0,
    "XLDRAGON3_FLAG": 0,
    "BOSS_XLDRAGON1": 0,
    "BOSS_XLDRAGON2": 0,
    "BOSS_XLARMOR1": 0,
    "BOSS_XLARMOR2": 0,
    "XLARMOR1": 0,
    "XLARMOR2": 0,
    "BOSS_XLCRAB": 0,
    "BOSS_XLPINCER": 0,
    "BOSS_GALLO": 0,
    "MASK_GOLD": 0,
    "MASK_SILVER": 0,
    "MASK_LEFT": 0,
    "MASK_RIGHT": 0,
    "MILK": 0,
    "MILK2": 0,
    "FISHMAN_1": 0,
    "LIZARD1_2": 0,
    "LIZARD2_3": 0,
    "ARMOR_6": 0,
    "ARMORSPEAR_6": 0,
    "MERMA1_3": 0,
    "MERMA2_4": 0,
    "BOSS_MERMAN": 0,
    "MIGNO1_5": 0,
    "MIGNO3_5": 0,
    "MIGNO_3_5SWARM": 0,
    "JELLYFISH": 0,
    "JELLYFISH2": 0,
    "JELLYFISH2_SWARM": 0,
    "PILE1": 0,
    "PILE2": 0,
    "PILE3": 0,
    "SKELENIN1": 0,
    "SKELENIN2": 0,
    "SKELEWING": 0,
    "XLARMOR_SWORD": 0,
    "XLTRITON": 0,
    "BULLET_1": 0,
    "BULLET_2": 0,
    "BULLET_3": 0,
    "BULLET_W": 0,
    "BULLET_Z": 0,
    "PATROL_XLARMOR_SWORD": 0,
    "PATROL_XLARMOR_1": 0,
    "PATROL_SKELEWING": 0,
    "PATROL_MIGNO_3_5SWARM": 0,
    "PATROL_ARMOR_6": 0,
    "PATROL_SKELEWING_BIG": 0,
    "PATROL_WITCH": 0,
    "GOLEM1": 0,
    "XLCHIMERA": 0,
    "XLCOCKATRICE": 0,
    "XLGOLEM1": 0,
    "XLGOLEM2": 0,
    "XLGOLEM3": 0,
    "XLGOLEM4": 0,
    "BOSS_XLCHIMERA": 0,
    "XLCOCKATRICE_GOLD": 0,
    "BOSS_XLTRITON": 0,
    "BOSS_PILE3": 0,
    "BOSS_MIGNO2_5": 0,
    "BOSS_MIGNO2_5_L": 0,
    "BOSS_ARMOR1": 0,
    "BOSS_XLCOCKATRICE": 0,
    "BOSS_XLGOLEM1": 0,
    "BOSS_XLGOLEM2": 0,
    "BOSS_XLARMOR": 0,
    "BOSS_XLGOLEM1_29": 0,
    "BOSS_XLGOLEM2_29": 0,
    "BOSS_MADDENER_NORMAL": 0,
    "TRAINEE_Y": 0,
    "FANGEL1": 0,
    "FANGEL2": 0,
    "FANGEL3": 0,
    "BOSS_FANGEL3": 0,
    "BOSS_DROWNER_NORMAL": 0,
    "TRAINEE_B": 0,
    "KALI1": 0,
    "KALI2": 0,
    "KALI2_FAST": 0,
    "SUCCUBUS": 0,
    "BOSS_SUCCUBUS": 0,
    "BOSS_STALKER_NORMAL": 0,
    "TRAINEE_G": 0,
    "ARMOR_FIRE": 0,
    "ARMOR_SWORD": 0,
    "XLARMOR_GOLD": 0,
    "XLARMOR_GREEN": 0,
    "BOSS_XLARMOR_GREEN": 0,
    "BOSS_TRICKSTER_NORMAL": 0,
    "TRAINEE_P": 0,
    "DEMON": 0,
    "DEMON_FAST": 0,
    "XLDEMON": 0,
    "XLDEMON2": 0,
    "XLARCHDEMON": 0,
    "BOSS_XLARCHDEMON": 0,
    "POLTER_GEM": 0,
    "POLTER_GEM_STATIC": 0,
    "STAGEKILLER": 0,
    "STAGEKILLER2": 0,
    "TRAINEE": 0,
    "TRAINEE_R": 0,
    "BOSS_TRINACRIA": 0,
    "ANGEL1": 0,
    "ANGEL2": 0,
    "ANGEL3": 0,
    "TRINACRIA": 0,
    "BOSS_EYE2": 0,
    "TRAINEE_ANY": 0,
    "BOSS_ENDER": 0,
    "BULLET_SCYTHE": 0,
    "BOSS_XLCRAB_RASH": 0,
    "BOSS_ENDER_RASH": 0,
    "BOSS_DROWNER_RASH": 0,
    "BOSS_DRAGOGION": 0,
    "BOSS_GIANT_MIMIC1": 0,
    "BOSS_GIANT_MIMIC2": 0,
    "BOSS_GIANT_MIMIC3": 0,
    "MOLISANO_BASE": 0,
    "MOLISANO_SECCO": 0,
    "MOLISANO_BELLO": 0,
    "MOLISANO_GROSSO": 0,
    "MOLISANO_GIALLO": 0,
    "MOLISANO_ROSSO": 0,
    "MOLISANO_FAGIOLO": 0,
    "MOLISANO_COLONNA": 0,
    "MOLISANO_VECCHIO": 0,
    "MOLISANO_ANFORA": 0,
    "MOON_ANFORA": 0,
    "MOON_JELLYFISH": 0,
    "MOON_CRABBINO": 0,
    "MOON_BOSS_CRABBINO": 0,
    "MOON_SNEK": 0,
    "MOON_SNEK_GREEN": 0,
    "MOON_SNEK_RED": 0,
    "MOON_GHOST": 0,
    "MOON_SHADEBLUE": 0,
    "MOON_FISHMAN": 0,
    "MOON_XLTRITON": 0,
    "MOON_MEDUSA1": 0,
    "MOON_MEDUSA2": 0,
    "MOON_NIGHTSHADE": 0,
    "MOON_GARLIC": 0,
    "MOON_BOSS_NIGHTSHADE": 0,
    "MOON_BOSS_GARLIC": 0,
    "MOON_EYE1": 0,
    "MOON_EYE2": 0,
    "MOON_EYE3": 0,
    "MOON_EYE1S": 0,
    "MOON_EYE2S": 0,
    "MOON_EYE3S": 0,
    "MOON_TRINACRIA": 0,
    "MOON_TRINACRIA_X": 0,
    "MOON_MASK1": 0,
    "MOON_MASK2": 0,
    "MOON_MASK3": 0,
    "MOON_MASK4": 0,
    "MOON_MASK5": 0,
    "MOON_BAT": 0,
    "MOON_BAT_PROJECTILE": 0,
    "MOON_SHADE": 0,
    "BOSS_XLMADDENER": 0,
    "UNDEADHEAD": 0,
    "UNDEADEYES": 0,
    "DIRECTER": 0,
    "D_CLUSTER_COINS": 0,
    "D_CLUSTER_GEMS": 0,
    "D_MASK_SUN": 0,
    "D_MASK_MOON": 0,
    "D_MASK_CITY": 0,
    "D_MASK_VOLCANO": 0,
    "D_MASK_WINDS": 0,
    "D_MASK_GREED": 0,
    "D_MASK_VOID": 0,
    "D_SKULL": 0,
    "D_EYE": 0,
    "BULLET_EGG": 0,
    "BULLET_EYE": 0,
    "D_WEAK_REAPER_A": 0,
    "D_WEAK_REAPER_B": 0,
    "D_WEAK_REAPER_C": 0,
    "D_WEAK_REAPER_D": 0,
    "D_WEAK_REAPER_E": 0,
    "D_WEAK_EYE": 0,
    "BOSS_SHARD_INFERNAS": 0,
    "XLSWORDIAN_V": 0,
    "XLSWORDIAN_AGGRO": 0,
    "BOSS_XLSWORDIAN": 0,
    "BOSS_XLSWORDIAN_2": 0,
    "BRIDGE_MINION": 0,
    "BRIDGE_TETRA": 0,
    "BRIDGE_ARMOR": 0,
    "BRIDGE_TRAINEE": 0,
    "BRIDGE_BOSS": 0,
    "MS_HITOT": 0,
    "MS_KAPPA": 0,
    "MS_MIKOS": 0,
    "MS_ONI1": 0,
    "MS_ONIWIND": 0,
    "MS_ONITHUNDER": 0,
    "MS_SPIRIT1": 0,
    "MS_SPIRIT1_SWARM": 0,
    "MS_SPIRIT2": 0,
    "MS_SPIRIT2_SWARM": 0,
    "MS_TANUKI": 0,
    "MS_TENGU": 0,
    "MS_TSUCHIGUMO": 0,
    "MS_TSUCHINOKO": 0,
    "MS_YAMAMBA1": 0,
    "MS_YAMAMBA2": 0,
    "MS_KAMAITACHI": 0,
    "MS_RAIJU": 0,
    "MS_OROCHIMARIO": 0,
    "MS_NINETYNINE": 0,
    "MS_GOSHADOKURO": 0,
    "MS_FLOWER1": 0,
    "MS_FLOWER2": 0,
    "MS_BOSS_SPIRIT": 0,
    "MS_BOSS_SPIRIT2": 0,
    "MS_BOSS_RAIJU": 0,
    "MS_BOSS_KAMAITACHI": 0,
    "MS_BOSS_TENGU": 0,
    "MS_BOSS_TANUKI": 0,
    "MS_BOSS_ONIWIND": 0,
    "MS_BOSS_ONITHUNDER": 0,
    "MS_BOSS_TSUCHIGUMO": 0,
    "MS_EVILSPIRIT": 0,
    "MS_OROCHIHEAD": 0
  },
  "PickupCount": {
    "VOID": 0,
    "WHIP": 0,
    "COIN": 331,
    "COINBAG1": 38,
    "COINBAG2": 5,
    "COINBAGMAX": 2,
    "GEM": 9372,
    "CLOVER": 1,
    "GILDED": 2,
    "ROSARY": 4,
    "VACUUM": 1,
    "OROLOGION": 7,
    "ROAST": 30,
    "NFT": 0,
    "TREASURE": 19,
    "ROSARYX": 0,
    "WEAPON": 0,
    "MOONGATE": 0,
    "COFFIN": 0,
    "COFFINX": 0,
    "COFFIN_EMPTY": 0,
    "MERCHANT": 0,
    "HEALER": 0,
    "PURIFY": 0,
    "PURIFY2": 0,
    "DIRECTER": 0,
    "LITTLEHEART": 0,
    "STATS_TREASURE_1": 17,
    "STATS_TREASURE_2": 2,
    "STATS_TREASURE_3": 0,
    "DUMMY_LIGHTSOURCE": 0,
    "DUMMY_BANISH": 0,
    "DUMMY_SKIP": 0,
    "DUMMY_REROLL": 0,
    "DUMMY_ARC": 0,
    "DUMMY_REVIVAL": 0,
    "ALWAYS_COINBAG2": 0,
    "ALWAYS_ROAST": 0,
    "RELIC": 0,
    "RELIC_BANGER": 0,
    "RELIC_MAP": 0,
    "RELIC_TEAR": 0,
    "RELIC_RANDOMAZZO": 0,
    "RELIC_GLASSMASK": 0,
    "RELIC_GOLDENEGG": 0,
    "RELIC_YELLOW": 0,
    "RELIC_NOSEGLASSES": 0,
    "RELIC_GRIMOIRE": 0,
    "RELIC_SECRETS": 0,
    "RELIC_GOUDA": 0,
    "RELIC_GGOSPEL": 0,
    "RELIC_MIRROR": 0,
    "RELIC_TRUMPET": 0,
    "COSMO_PAVONE": 0,
    "[object Object]": 1
  },
  "DestroyedCount": {
    "CANDLE": 0,
    "CANDELABRA": 0,
    "BRAZIER": 268,
    "BRAZIER2": 0,
    "LAMPOST": 0,
    "CART": 0,
    "WINDOW": 0
  },
  "StageCompletionLog": {
    "ANTONIO": [],
    "IMELDA": [],
    "PASQUALINA": [
      "FOREST"
    ],
    "GENNARO": [],
    "CIRO": [],
    "PORTA": [],
    "LAMA": [],
    "CAMILLO": [],
    "GERMANA": [],
    "DOMMARIO": [],
    "CROCI": [],
    "CRISTINA": [],
    "PUGNALA": [],
    "GIOVANNA": [],
    "POPPEA": [],
    "CONCETTA": [],
    "MORTACCIO": [],
    "CAVALLO": [],
    "MARIA": [],
    "TATANKA": [],
    "AMBROGIO": [],
    "PINO": [],
    "FEBBRA": [],
    "ASSUNTA": [],
    "EXDASH": [],
    "PANINI": [],
    "SMITH": [],
    "ARENGIJUS": [],
    "NEO": [],
    "AVATAR": [],
    "GRAZIELLA": [],
    "VERANDA": [],
    "PAVONE": [],
    "PEPPINO": [],
    "PANTALONE": [],
    "FINO": [],
    "BOROS": [],
    "DRAGOGION": [],
    "NOSTRO": [],
    "SIGMA": [],
    "SCOREJ": [],
    "MIANG": [],
    "MENYA": [],
    "SYUUTO": [],
    "ONNA": [],
    "MCCOY": [],
    "MEGAMENYA": [],
    "MEGASYUUTO": [],
    "TONY": []
  },
  "CharacterStageData": {
    "ANTONIO": [
      {
        "complete": 0,
        "hyper": false,
        "hurry": false,
        "inverse": false,
        "survivedMinutes": 24,
        "startedRun": 11,
        "type": "FOREST"
      }
    ],
    "IMELDA": [
      {
        "complete": 0,
        "hyper": false,
        "hurry": false,
        "inverse": false,
        "survivedMinutes": 1,
        "startedRun": 3,
        "type": "FOREST"
      }
    ],
    "PASQUALINA": [
      {
        "complete": 1,
        "hyper": false,
        "hurry": false,
        "inverse": false,
        "survivedMinutes": 31,
        "startedRun": 3,
        "type": "FOREST"
      },
      "FOREST"
    ],
    "EXDASH": [
      {
        "complete": 0,
        "hyper": false,
        "hurry": false,
        "inverse": false,
        "survivedMinutes": 0,
        "startedRun": 1,
        "type": "FOREST"
      }
    ]
  },
  "CharacterEnemiesKilled": {
    "ANTONIO": 1432,
    "IMELDA": 140,
    "PASQUALINA": 99
  },
  "CharacterSurvivedMinutes": {
    "ANTONIO": 13,
    "IMELDA": 1,
    "PASQUALINA": 1,
    "GENNARO": 0,
    "CIRO": 0,
    "PORTA": 0,
    "LAMA": 0,
    "CAMILLO": 0,
    "GERMANA": 0,
    "DOMMARIO": 0,
    "CROCI": 0,
    "CRISTINA": 0,
    "PUGNALA": 0,
    "GIOVANNA": 0,
    "POPPEA": 0,
    "CONCETTA": 0,
    "MORTACCIO": 0,
    "CAVALLO": 0,
    "MARIA": 0,
    "TATANKA": 0,
    "AMBROGIO": 0,
    "PINO": 0,
    "FEBBRA": 0,
    "ASSUNTA": 0,
    "EXDASH": 0,
    "PANINI": 0,
    "SMITH": 0,
    "ARENGIJUS": 0,
    "NEO": 0,
    "AVATAR": 0,
    "GRAZIELLA": 0,
    "VERANDA": 0,
    "PAVONE": 0,
    "PEPPINO": 0,
    "PANTALONE": 0,
    "BOROS": 0,
    "DRAGOGION": 0,
    "NOSTRO": 0,
    "SIGMA": 0,
    "SCOREJ": 0
  },
  "MusicSelectionPerStage": {},
  "checksum": "6d81e029d5f9211a3e3e8921504fc4d26e5b087c0e913278301a2c6799186d5b",
  "EggData": {},
  "Didit": false,
  "Seals": "0",
  "SealedItems": [],
  "SealedWeapons": [],
  "MainMenuBG": "CLASSIC",
  "SelectedJoystickType": "Default"
}
export default template
